### PR TITLE
creation of summary.html landing page as well as a css and html that …

### PR DESCRIPTION
**Pull request by braddavistech**
…provides more stylings including having the image spin on the page and stop when the cursor hovers over it. The summary.html has no custom stylings done and connects to style.css. The summaryWithSpinPic.html is connected to summaryWithSpinPic.css. It has the stylings to create the spinning pic as well as some internal adjustments to the style inside the html. This will eventually replace index.html as the landing page.

### CODE REVIEW

**Comment by jasehackman** [comment]
Right now if I scroll all the way to the bottom I can't see the bottom line of text. It is covered by the footer. We will have to find a fix for that tomorrow.

**Comment by braddavistech** [comment]
If you look at the summarySpinPic file, I adjusted it out. I left the formatting on the summary file the way it was so that it works with the style.css. I sent Nolan a message on fixing the article__section bottom-margin to prevent it being hidden by footer.

**Comment by jasehackman** [comment]
perfect 👍

**Comment by danielreedcombs** [comment]
👍

**Comment by braddavistech** [comment]
Closing pull request and only sending back summary.html.

**Pull request closed without merging**
