### PR TITLE
news feed edits and new styling sheet

### PR DESCRIPTION
**Pull request by danielreedcombs**
- Created danielstyles css page
- Images to image folder (happyWillyHung.jpg, motivation.jpg, williamsheriff.jpg)
- Attached style sheet, created text content, and added images to news.html

Thanks!

### CODE REVIEW

**Comment by braddavistech** [comment]
The individual divisions should all be in the section element so that it is only on the same element and on a continuous background. Also for some reason, the speaking to the masses img is compressed.

**Comment by jasehackman** [comment]
put text content inside of <p> instead of <h> tags

**Comment by danielreedcombs** [comment]
Final changes:
- css edit to make pictures appear away from text
- and fixed the text into the p tag instead of the h2 tag.

🐷

**Comment by racheldaniel** [comment]
👍

**Comment by braddavistech** [comment]
👍

**Comment by Nolan-Little** [comment]
👍

**Comment by braddavistech** [comment]
👍

**Comment by jasehackman** [comment]
👍

**Pull request merged**
