### PR TITLE
create extra report page and corresponding style sheet

### PR DESCRIPTION
**Pull request by Nolan-Little**
extra report page with style sheet. also includes an added image for the page.

### CODE REVIEW

**Comment by danielreedcombs** [comment]
👍

**Comment by Nolan-Little** [comment]
git checkout nl-extrasPage

**Comment by braddavistech** [comment]
Looks good. If you are going to use the hover to grow the image, have you though of either making the initial image smaller, or the hover size larger to show a bigger contrast?

**Comment by racheldaniel** [comment]
👍

**Comment by jasehackman** [comment]
👍

**Pull request merged**
