### PR TITLE
finished personal page, added  associated images and css

### PR DESCRIPTION
**Pull request by racheldaniel**
feel free to check it out and make suggestions:
git fetch --all
git checkout rd-personal

### CODE REVIEW

**Comment by Nolan-Little** [comment]
Looks good except for the wedding image .personal--img is stretching strangly.

**Comment by racheldaniel** [comment]
Wedding image is now scaling properly

**Comment by jasehackman** [comment]
All of your content section are center justified except for current life. Current life is left justified. You might want to change it for consistency.

**Comment by Nolan-Little** [comment]
👍  on the wedding photo

**Comment by racheldaniel** [comment]
Centered all contents and added a period after website link

**Comment by braddavistech** [comment]
Looks good. 👍

**Comment by jasehackman** [comment]
👍

**Comment by Nolan-Little** [comment]
👍

**Pull request merged**
