### PR TITLE
Js audio

### PR DESCRIPTION
**Pull request by Nolan-Little**
Nolan Little
git checkout jsAudio
please check youtube embed on extra's page at the bottom.
please check audio functionality on all pages on mouse over of portrait.

### CODE REVIEW

**Comment by racheldaniel** [comment]
👍  You definitely gave your best

**Comment by jasehackman** [comment]
👍 

but did you give it your best?

**Comment by danielreedcombs** [comment]
:thumb

**Comment by braddavistech** [comment]
👍

**Pull request merged**
